name: Publish LokerPuller to PyPI
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-n-publish:
    name: Build and publish LokerPuller to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build distribution 📦
        run: python -m build

      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags') || github.event_name == 'workflow_dispatch'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}